/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2020-02-03 09:32:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class datatable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no\" name=\"viewport\">\r\n");
      out.write("  <title>Otika - Admin Dashboard Template</title>\r\n");
      out.write("  <!-- General CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"adminResources/css/app.min.css\">\r\n");
      out.write("  <!-- Template CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"adminResources/css/datatables.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"adminResources/css/dataTables.bootstrap4.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"adminResources/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"adminResources/css/components.css\">\r\n");
      out.write("  <!-- Custom style CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"adminResources/css/custom.css\">\r\n");
      out.write("  <link rel='shortcut icon' type='image/x-icon' href='adminResources/image/favicon.ico' />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"loader\"></div>\r\n");
      out.write("  <div id=\"app\">\r\n");
      out.write("    <div class=\"main-wrapper main-wrapper-1\">\r\n");
      out.write("      <div class=\"navbar-bg\"></div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- HEADER -->\r\n");
      out.write("      \r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- MENU -->\r\n");
      out.write("      \r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("      \r\n");
      out.write("       <!-- Main Content -->\r\n");
      out.write("      <div class=\"main-content\">\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("          <div class=\"section-body\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-12\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-header\">\r\n");
      out.write("                    <h4>Your Orders</h4>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                      <table class=\"table table-striped table-hover\" id=\"tableExport\" style=\"width:100%;\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <th>OrderId</th>\r\n");
      out.write("                            <th>Customer Name</th>\r\n");
      out.write("                            <th>Products</th>\r\n");
      out.write("                            <th>Total Bill</th>\r\n");
      out.write("                            <th>Order Status</th>\r\n");
      out.write("                            <th>Accept</th>\r\n");
      out.write("                            <th>Reject</th>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td><p>Tiger Nixon</p><p>Tiger Nixon</p></td>\r\n");
      out.write("                            <td>System Architect</td>\r\n");
      out.write("                            <td>Edinburgh</td>\r\n");
      out.write("                            <td>61</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <div class=\"badge badge-success badge-shadow\">Completed</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            \r\n");
      out.write("                            <td><a href=\"#\" class=\"btn btn-primary\">Accept</a></td>\r\n");
      out.write("                            <td><a href=\"#\" class=\"btn btn-primary\">Reject</a></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"settingSidebar\">\r\n");
      out.write("          <a href=\"javascript:void(0)\" class=\"settingPanelToggle\"> <i class=\"fa fa-spin fa-cog\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"settingSidebar-body ps-container ps-theme-default\">\r\n");
      out.write("            <div class=\" fade show active\">\r\n");
      out.write("              <div class=\"setting-panel-header\">Setting Panel\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"p-15 border-bottom\">\r\n");
      out.write("                <h6 class=\"font-medium m-b-10\">Select Layout</h6>\r\n");
      out.write("                <div class=\"selectgroup layout-color w-50\">\r\n");
      out.write("                  <label class=\"selectgroup-item\">\r\n");
      out.write("                    <input type=\"radio\" name=\"value\" value=\"1\" class=\"selectgroup-input-radio select-layout\" checked>\r\n");
      out.write("                    <span class=\"selectgroup-button\">Light</span>\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <label class=\"selectgroup-item\">\r\n");
      out.write("                    <input type=\"radio\" name=\"value\" value=\"2\" class=\"selectgroup-input-radio select-layout\">\r\n");
      out.write("                    <span class=\"selectgroup-button\">Dark</span>\r\n");
      out.write("                  </label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"p-15 border-bottom\">\r\n");
      out.write("                <h6 class=\"font-medium m-b-10\">Sidebar Color</h6>\r\n");
      out.write("                <div class=\"selectgroup selectgroup-pills sidebar-color\">\r\n");
      out.write("                  <label class=\"selectgroup-item\">\r\n");
      out.write("                    <input type=\"radio\" name=\"icon-input\" value=\"1\" class=\"selectgroup-input select-sidebar\">\r\n");
      out.write("                    <span class=\"selectgroup-button selectgroup-button-icon\" data-toggle=\"tooltip\"\r\n");
      out.write("                      data-original-title=\"Light Sidebar\"><i class=\"fas fa-sun\"></i></span>\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <label class=\"selectgroup-item\">\r\n");
      out.write("                    <input type=\"radio\" name=\"icon-input\" value=\"2\" class=\"selectgroup-input select-sidebar\" checked>\r\n");
      out.write("                    <span class=\"selectgroup-button selectgroup-button-icon\" data-toggle=\"tooltip\"\r\n");
      out.write("                      data-original-title=\"Dark Sidebar\"><i class=\"fas fa-moon\"></i></span>\r\n");
      out.write("                  </label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"p-15 border-bottom\">\r\n");
      out.write("                <h6 class=\"font-medium m-b-10\">Color Theme</h6>\r\n");
      out.write("                <div class=\"theme-setting-options\">\r\n");
      out.write("                  <ul class=\"choose-theme list-unstyled mb-0\">\r\n");
      out.write("                    <li title=\"white\" class=\"active\">\r\n");
      out.write("                      <div class=\"white\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"cyan\">\r\n");
      out.write("                      <div class=\"cyan\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"black\">\r\n");
      out.write("                      <div class=\"black\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"purple\">\r\n");
      out.write("                      <div class=\"purple\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"orange\">\r\n");
      out.write("                      <div class=\"orange\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"green\">\r\n");
      out.write("                      <div class=\"green\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"red\">\r\n");
      out.write("                      <div class=\"red\"></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"p-15 border-bottom\">\r\n");
      out.write("                <div class=\"theme-setting-options\">\r\n");
      out.write("                  <label class=\"m-b-0\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"custom-switch-checkbox\" class=\"custom-switch-input\"\r\n");
      out.write("                      id=\"mini_sidebar_setting\">\r\n");
      out.write("                    <span class=\"custom-switch-indicator\"></span>\r\n");
      out.write("                    <span class=\"control-label p-l-10\">Mini Sidebar</span>\r\n");
      out.write("                  </label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"p-15 border-bottom\">\r\n");
      out.write("                <div class=\"theme-setting-options\">\r\n");
      out.write("                  <label class=\"m-b-0\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"custom-switch-checkbox\" class=\"custom-switch-input\"\r\n");
      out.write("                      id=\"sticky_header_setting\">\r\n");
      out.write("                    <span class=\"custom-switch-indicator\"></span>\r\n");
      out.write("                    <span class=\"control-label p-l-10\">Sticky Header</span>\r\n");
      out.write("                  </label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"mt-4 mb-4 p-3 align-center rt-sidebar-last-ele\">\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-icon icon-left btn-primary btn-restore-theme\">\r\n");
      out.write("                  <i class=\"fas fa-undo\"></i> Restore Default\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"footer-left\">\r\n");
      out.write("          Copyright &copy; 2019 <div class=\"bullet\"></div> Design By <a href=\"#\">Redstar</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-right\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- General JS Scripts -->\r\n");
      out.write("  <script src=\"adminResources/js/app.min.js\"></script>\r\n");
      out.write("  <!-- JS Libraies -->\r\n");
      out.write("  <!-- Page Specific JS File -->\r\n");
      out.write("  <script src=\"adminResources/js/datatables.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/buttons.flash.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/jszip.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/pdfmake.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/vfs_fonts.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/buttons.print.min.js\"></script>\r\n");
      out.write("  <script src=\"adminResources/js/datatables.js\"></script>\r\n");
      out.write("  <!-- Template JS File -->\r\n");
      out.write("  <script src=\"adminResources/js/scripts.js\"></script>\r\n");
      out.write("  <!-- Custom JS File -->\r\n");
      out.write("  <script src=\"adminResources/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
